services:
  backend:
    image: s2-analyzer-backend
    build: ./backend
    volumes:
      - ./data:/app/data
    ports:
      - "8001:8001"
    environment:
      LOG_LEVEL: info
      DATABASE_URL: sqlite:///data/database.sqlite3

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
