enum CommodityQuantity{
    /*ELECTRIC.POWER.L1,
    ELECTRIC.POWER.L2,
    ELECTRIC.POWER.L3,
    ELECTRIC.POWER.3_PHASE_SYMMETRIC,
    NATURAL_GAS.FLOW_RATE,
    HYDROGEN.FLOW_RATE,
    HEAT.TEMPERATURE,
    HEAT.FLOW_RATE,
    HEAT.THERMAL_POWER,
    OIL.FLOW_RATE,*/
}