export enum CommodityQuantity {
  ELECTRIC_POWER_L1 = "ELECTRIC.POWER.L1",
  ELECTRIC_POWER_L2 = "ELECTRIC.POWER.L2",
  ELECTRIC_POWER_L3 = "ELECTRIC.POWER.L3",
  ELECTRIC_POWER_3_PHASE_SYMMETRIC = "ELECTRIC.POWER.3_PHASE_SYMMETRIC",
  NATURAL_GAS_FLOW_RATE = "NATURAL_GAS.FLOW_RATE",
  HYDROGEN_FLOW_RATE = "HYDROGEN.FLOW_RATE",
  HEAT_TEMPERATURE = "HEAT.TEMPERATURE",
  HEAT_FLOW_RATE = "HEAT.FLOW_RATE",
  HEAT_THERMAL_POWER = "HEAT.THERMAL_POWER",
  OIL_FLOW_RATE = "OIL.FLOW_RATE",
}
