export enum ControlType{
    POWER_ENVELOPE_BASED_CONTROL = "POWER_ENVELOPE_BASED_CONTROL",
    POWER_PROFILE_BASED_CONTROL = "POWER_PROFILE_BASED_CONTROL",
    OPERATION_MODE_BASED_CONTROL = "OPERATION_MODE_BASED_CONTROL",
    FILL_RATE_BASED_CONTROL = "FILL_RATE_BASED_CONTROL",
    DEMAND_DRIVEN_BASED_CONTROL = "DEMAND_DRIVEN_BASED_CONTROL",
    NOT_CONTROLABLE = "NOT_CONTROLABLE",
    NO_SELECTION = "NO_SELECTION",
}