export enum ReceptionStatusValues{
    INVALID_DATA = "INVALID_DATA",
    INVALID_MESSAGE = "INVALID_MESSAGE",
    INVALID_CONTENT = "INVALID_CONTENT",
    TEMPORARY_ERROR = "TEMPORARY_ERROR",
    PERMANENT_ERROR = "PERMANENT_ERROR",
    OK = "OK"
}