export enum RevokableObjects {
  PEBC_PowerConstraints = "PEBC.PowerConstraints",
  PEBC_EnergyConstraint = "PEBC.EnergyConstraint",
  PEBC_Instruction = "PEBC.Instruction",
  PPBC_PowerProfileDefinition = "PPBC.PowerProfileDefinition",
  PPBC_ScheduleInstruction = "PPBC.ScheduleInstruction",
  PPBC_StartInterruptionInstruction = "PPBC.StartInterruptionInstruction",
  PPBC_EndInterruptionInstruction = "PPBC.EndInterruptionInstruction",
  OMBC_SystemDescription = "OMBC.SystemDescription",
  OMBC_Instruction = "OMBC.Instruction",
  FRBC_SystemDescription = "FRBC.SystemDescription",
  FRBC_Instruction = "FRBC.Instruction",
  DDBC_SystemDescription = "DDBC.SystemDescription",
  DDBC_Instruction = "DDBC.Instruction",
}
